_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: e5a8c348-d542-46fe-9fec-f49b7d45df75
name: 'Domino Sugar'
mail: sanjay.so@hcl.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/4
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
