name: fcc
recipe: drupal9
config:
  webroot: docroot
proxy:
  appserver:
    - fcc.lndo.site
    - dominosugar.lndo.site
services:
  fcc:
    type: mysql:5.7
    creds:
      user: fcc
      password: fcc
      database: fcc
  dominosugar:
    type: mysql:5.7
    creds:
      user: dominosugar
      password: dominosugar
      database: dominosugar
      pma:
      type: phpmyadmin:5.1
      hosts:
        - database
# for phpcs
  build:
      - "mkdir -p /app/coder && cd /app/coder && composer global require drupal/coder:8.3.13"
      - "/app/coder/vendor/bin/phpcs --config-set installed_paths /app/coder/vendor/drupal/coder/coder_sniffer"

