name: fccwebd9
recipe: acquia
config:
  webroot: docroot
  acli_version: latest
  ah_application_uuid: 46d7c5ce-b9cb-488a-91cd-8af0b79bacbf
  php: '7.4'
  cache: true
  type: memchached:1.6
  composer_version: '2'
  inbox: true
proxy:
  appserver:
    - fcc.lndo.site
    - dominosugar.lndo.site
services:
  fcc:
    type: mysql:5.7
    creds:
      user: fcc
      password: fcc
      database: fcc
  dominosugar:
    type: mysql:5.7
    creds:
      user: dominosugar
      password: dominosugar
      database: dominosugar
  pma:
      type: phpmyadmin:5.1
      hosts:
        - database
# for phpcs
  build:
      - "mkdir -p /app/coder && cd /app/coder && composer global require drupal/coder:8.3.13"
      - "/app/coder/vendor/bin/phpcs --config-set installed_paths /app/coder/vendor/drupal/coder/coder_sniffer"

