name: PHP phpcs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

#    - name: Validate composer.json and composer.lock
#     run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer update --prefer-dist --no-progress
      
    - name: Install phpcs
      run: curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
    - name: Install phpcbf
      run: curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar
      
    - name: Then test the downloaded phpcs.phar
      run: php phpcs.phar -h
    - name: Then test the downloaded phpcbf.phar
      run:  php phpcbf.phar -h


    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
    - name: Run phpcs
      run: composer phpcs
    - name: Run phpcbf
      run: composer phpcbf
