 name: push GitHub to Acquia Git

on:
  pull_request:
     types:
         - closed
     branches:
         - master
 jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
   
    
   steps:
    - name: Install git
      run: |
        apt-get install -y git
        git --version
        echo "Path is ... $PATH"
        PATH=$PATH:$(which git)
        echo "Path is ... $PATH"
        
 


 
