name: Sonar_scanning
on:
  workflow_run:
    workflows: ["PHP phpcs"]
    types:
      - completed
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
      
        with:
         projectBaseDir: docroot
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        with:
         projectBaseDir: my-custom-directory
         args: >
          -Dsonar.sources=docroot/
          -Dsonar.test.exclusions=docroot/core/**
          -Dsonar.test.exclusions=docroot/vendor/**
          -Dsonar.tests=tests/
          -Dsonar.verbose=true
  
env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

